[package]
name = "pad-extract"
version = "0.2.1"
edition = "2024"

[lib]
name = "pad"
path = "src/lib.rs"

[[bench]]
name = "meta-bench"
harness = false

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive", "extern_crate_alloc"] }
byteorder = "1.5.0"
encoding_rs = "0.8.35"
icefast = "2.0.1"
memchr = "2.8.0"
nohash-hasher = "0.2.0"
quicklz = "0.3.1"
rayon = "1.11.0"
rdst = "0.20.14"
regex = "1.12.3"
windows-sys = { version = "0.61.2", features = [
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_Foundation",
    "Win32_Security",
] }

[dev-dependencies]
bencher = "0.1.5"
lazy_static = "1.5.0"
mimalloc = { version = "0.1.48", default-features = false }

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
panic = "abort"
